---
jobs:
  - name: build
    plan:
      - get: moonfolio-frontend
        trigger: true

      - task: npm-build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node, tag: "8" }
          inputs:
            - name: moonfolio-frontend
          run:
            path: moonfolio-frontend/ci/scripts/build.sh

resources:
  - name: moonfolio-frontend
    type: git
    source:
      uri: https://github.com/Moonfolio/moonfolio-frontend
      branch: master
